### ISSUE TITLE
NPE in JaxRSServerContainer.getHttpService()

### ISSUE THREAD

**Issue by scottslewis** [ECF/JaxRSProviders#15]
java.lang.NullPointerException
at org.eclipse.ecf.provider.jaxrs.server.JaxRSServerContainer.getHttpService(JaxRSServerContainer.java:95)
at org.eclipse.ecf.provider.jaxrs.server.JaxRSServerContainer.exportRemoteService(JaxRSServerContainer.java:136)
at org.eclipse.ecf.remoteservice.RSARemoteServiceContainerAdapter$RSARemoteServiceRegistration.publish(RSARemoteServiceContainerAdapter.java:53)
at org.eclipse.ecf.remoteservice.RemoteServiceContainerAdapterImpl.registerRemoteService(RemoteServiceContainerAdapterImpl.java:123)
at org.eclipse.ecf.osgi.services.remoteserviceadmin.RemoteServiceAdmin.exportService(RemoteServiceAdmin.java:2156)

**Comment by scottslewis** [comment]
Fixed in 1.6.1 release
