### ISSUE TITLE
cxf repository should be absolute

### ISSUE THREAD

**Issue by tvogel8570** [ECF/JaxRSProviders#34]
When installing the feature with ` feature:install -v ecf-rs-distribution-jersey` in karaf-features.xml a warning is generated
```
18:32:08.572 WARN  [pipe-feature:install -v ecf-rs-distribution-jersey] Can't load features repository cxf
address-karaf    | java.lang.RuntimeException: URI is not absolute : cxf
address-karaf    |      at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:116)
address-karaf    |      at org.apache.karaf.features.internal.service.RepositoryImpl.<init>(RepositoryImpl.java:50)
address-karaf    |      at org.apache.karaf.features.internal.service.RepositoryCacheImpl.create(RepositoryCacheImpl.java:51)
address-karaf    |      at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatureCache(FeaturesServiceImpl.java:605)
address-karaf    |      at org.apache.karaf.features.internal.service.FeaturesServiceImpl.computeFeaturesToAdd(FeaturesServiceImpl.java:825)
address-karaf    |      at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:798)
address-karaf    |      at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:78)
address-karaf    |      at org.apache.karaf.features.command.FeaturesCommandSupport.execute(FeaturesCommandSupport.java:40)
address-karaf    |      at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84)
address-karaf    |      at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68)
address-karaf    |      at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86)
address-karaf    |      at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599)
address-karaf    |      at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526)
address-karaf    |      at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415)
address-karaf    |      at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416)
address-karaf    |      at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229)
address-karaf    |      at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59)
address-karaf    |      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
address-karaf    |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
address-karaf    |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
address-karaf    |      at java.lang.Thread.run(Thread.java:748)
address-karaf    | Caused by: java.lang.IllegalArgumentException: URI is not absolute
address-karaf    |      at java.net.URI.toURL(URI.java:1088)
address-karaf    |      at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:113)
address-karaf    |      ... 20 more
```

The repository reference in karaf-features.xml for cxf is relative `<repository>cxf</repository>` and should be absolute.

**Comment by scottslewis** [comment]
Fixed via above commit.  Closing.
